roteirizacao/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import EscolherPlanoView, CustomUserCreationView, atualizar_creditos, atualizar_senha,  autoriza_criar_rota, base2, buscar_pagamentos, buscar_user, contato, editar_pagamento, editar_user, enviar_email, excluir_pagamento, excluir_user, gerar_arquivo_gpx_view, lista_enderecos, adicionar_endereco, home, lista_pagamento, lista_user, pagamento_form, recuperar_senha, recursos, sobre, verificar_saldo
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name='home'),
    path('base2/', base2, name='base2'),
    path('sobre/', sobre, name='sobre'),
    path('recursos/', recursos, name='recursos'),
    path('contato/', contato, name='contato'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('signup/', CustomUserCreationView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('lista_enderecos', lista_enderecos, name='lista_enderecos'),
    path('adicionar/', adicionar_endereco, name='adicionar'),
    path('escolher_plano/', EscolherPlanoView.as_view(), name='escolher_plano'),
    path('enviar_email/', enviar_email, name='enviar_email'),
    path('verificar_saldo/', verificar_saldo, name='verificar_saldo'),
    path('lista_pagamento/', lista_pagamento, name='lista_pagamento'),
    path('pagamento/', pagamento_form, name='pagamento'),
    path('autoriza_criar_rota/', autoriza_criar_rota, name='autoriza_criar_rota'),
    path('buscar_pagamentos/', buscar_pagamentos, name='buscar_pagamentos'),
    path('editar_pagamento/<int:pagamento_id>/', editar_pagamento, name='editar_pagamento'),
    path('excluir_pagamento/<int:pagamento_id>/', excluir_pagamento, name='excluir_pagamento'),
    path('atualizar_creditos/', atualizar_creditos, name='atualizar_creditos'),
    path('lista_user/', lista_user, name='lista_user'),
    path('buscar_user/', buscar_user, name='buscar_user'),
    path('editar_user/<int:user_id>/', editar_user, name='editar_user'),
    path('excluir_user/<int:user_id>/', excluir_user, name='excluir_user'),
    path('recuperar-senha/', recuperar_senha, name='recuperar_senha'),
    path('atualizar-senha/', atualizar_senha, name='atualizar_senha'),
    path('gerar_arquivo_gpx/', gerar_arquivo_gpx_view, name='gerar_arquivo_gpx'),

]

roteirizacao_app/urls.py
from django.contrib import admin
from django.urls import path, include
from roteirizacao.views import signup
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roteirizacao.urls')),
    path('signup/', signup, name='signup'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

roteirizacao/models.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager, Permission, User
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('O campo de e-mail deve ser definido')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    choices_cargo = (
        ('U', 'Usuario'),
        ('Admin', 'Administrador'),
    )
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    cargo = models.CharField(max_length=5, choices=choices_cargo)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)

    objects = CustomUserManager()

    def delete(self, using=None, keep_parents=False):
        # Substituímos o método delete padrão para realizar um soft delete
        self.is_active = False
        self.save()

    # Adicione o related_name aqui
    groups = models.ManyToManyField('auth.Group', related_name='custom_user_set', blank=True)
    user_permissions = models.ManyToManyField('auth.Permission', related_name='custom_user_set', blank=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.cargo:
            self.cargo = 'U'  # Define um valor padrão para o cargo caso não seja especificado

    class Meta:
        permissions = [
            ("pode_add_endereco", "Pode Adicionar Endereco"),
            ("pode_alterar_endereco", "Pode Alterar Endereco"),
            ("pode_deletar_endereco", "Pode Deletar Endereco"),
            # Adicione permissões adicionais conforme necessário
        ]


# Tabela Endereco
class Endereco(models.Model):
    cep = models.CharField(max_length=10)
    logradouro = models.CharField(max_length=255)
    bairro = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    numero = models.CharField(max_length=10)
    estado = models.CharField(max_length=50)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)

    def __str__(self):
        return f"{self.cep}, {self.logradouro}, {self.bairro}, {self.cidade}, {self.numero}, {self.estado}, {self.latitude}, {self.longitude} "

# Tabela Viagem
class Viagem(models.Model):
    numero_viagem = models.CharField(max_length=50)
    parada = models.CharField(max_length=50)
    lougradouro = models.CharField(max_length=255)
    bairro = models.CharField(max_length=255)
    cidade = models.CharField(max_length=255)
    numero = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    longitude = models.CharField(max_length=255)



# Gerencia Pagementos
CustomUser = get_user_model()

class Pagamento(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)  # Use settings.AUTH_USER_MODEL
    codigo_pagamento = models.CharField(max_length=30, null=True)
    data_pagamento = models.DateField(null=True, blank=True)
    valido_ate = models.DateField(null=True, blank=True)
    quant_acesso = models.IntegerField(default=0)

    class Meta:
        permissions = [
            ("ver_pagamento", "Pode Ver Pagamento"),
            # Adicione permissões adicionais conforme necessário
        ]


class PagamentoForm(forms.ModelForm):
    # Define o campo de busca para selecionar uma instância existente do modelo Pagamento
    pagamento = forms.ModelChoiceField(
        queryset=Pagamento.objects.all(),
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Pesquisar pagamento'}),
        required=False
    )

    class Meta:
        model = Pagamento
        fields = '__all__'

    # Inclui a lógica para salvar a instância selecionada do pagamento se ela existir
    def save(self, commit=True):
        pagamento = self.cleaned_data.get('pagamento')
        if pagamento:
            return pagamento
        return super().save(commit=commit)

## Gerenciar Permissões - INICIO
class CustomPermissionGroup(Group):
    class Meta:
        proxy = True

## Gerenciar Permissões - FIM

roteirizacao/views.py
from email.headerregistry import Group
from imaplib import _Authenticator
import json
import logging
from django.views.generic import ListView
from multiprocessing import AuthenticationError
from pyexpat.errors import messages
from urllib.request import Request
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext
from django.test import RequestFactory
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser, Endereco, Viagem, Pagamento
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, get_user_model
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import View
from django.utils.decorators import method_decorator
from datetime import datetime, timedelta, timezone
from django.contrib.auth.models import Group, Permission
from django.views.decorators.csrf import csrf_exempt
import requests
from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.views.generic import ListView
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.db.models import Count
from django.db.models import Q
from .forms import ContatoForm, CustomUserCreationForm, CustomUserForm, PagamentoForm
from django.db.models import F
from icecream import ic
from django.contrib.auth.hashers import make_password
import gpxpy
import gpxpy.gpx
from geopy.geocoders import Nominatim


def home(request):
    # Obtenha o pagamento do usuário atual
    pagamento = None
    if request.user.is_authenticated:
        pagamento = Pagamento.objects.filter(usuario=request.user).order_by('-data_pagamento').first()
        ic(pagamento)

    # Renderize o template com o contexto
    return render(request, 'home.html', {'pagamento': pagamento})

def base2(request):
    # Renderize o template com o contexto
    return render(request, 'base2.html')

def sobre(request):
    # Renderize o template com o contexto
    return render(request, 'sobre.html')

def recursos(request):
    # Renderize o template com o contexto
    return render(request, 'recursos.html')

def contato(request):
    # Renderize o template com o contexto
    return render(request, 'contato.html')

def base(request):
    # Chamar a função autoriza_criar_rota para verificar a permissão do usuário
    mensagem = autoriza_criar_rota(request)

    # Obtenha o pagamento do usuário atual
    pagamento = None
    # Verifica se o usuário está autenticado
    if request.user.is_authenticated:
        # Obtém o pagamento do usuário atual
        pagamento = Pagamento.objects.filter(usuario=request.user).order_by('-data_pagamento').first()
        ic(pagamento)
    else:
        pagamento = None

    # Renderize o template com o contexto
    return render(request, 'base.html', {'pagamento': pagamento})

def pagamento_context_processor(request):
    usuario = request.user
    pagamento = None
    if usuario.is_authenticated:
        pagamento = Pagamento.objects.filter(usuario=usuario).order_by('-data_pagamento').first()
    return {'pagamento': pagamento}



logger = logging.getLogger(__name__)



@login_required
# @permission_required('roteirizacao_app.add_pagamento', raise_exception=True)
def pagamento_form(request):
    if request.method == 'POST':
        # Se a solicitação for POST, pode ser do formulário HTML ou do JSON
        if request.content_type == 'application/json':
            # Obter os dados JSON do corpo da solicitação
            json_data = json.loads(request.body)
            
            # Acessar os dados individuais
            usuario_id = json_data.get('usuario_id')
            data_pagamento = json_data.get('data_pagamento')
            codigo_pagamento = json_data.get('codigo_pagamento')
        else:
            # Se a solicitação for do formulário HTML
            form = PagamentoForm(request.POST)
            if form.is_valid():
                # Se o formulário for válido, salvar os dados do formulário
                pagamento = form.save(commit=False)
                pagamento.valido_ate = pagamento.data_pagamento + timedelta(days=30)
                pagamento.quant_acesso = 0  # Ou o valor que desejar
                pagamento.save()
                return redirect('home')  # Redirecionar para a mesma página após o envio do formulário
            else:
                # Se o formulário não for válido, retornar uma resposta de erro
                return JsonResponse({'error': 'Formulário inválido.'}, status=400)

        # Criar uma instância do modelo Pagamento com os dados fornecidos
        pagamento = Pagamento.objects.create(
            usuario_id=usuario_id,
            data_pagamento=data_pagamento,
            valido_ate=timezone.now() + timedelta(days=30),  # Exemplo de data de validade
            quant_acesso= 0,  # Exemplo de quantidade de acesso inicial
            codigo_pagamento=codigo_pagamento
        )
        
        # Salvar o objeto Pagamento no banco de dados
        pagamento.save()

        # Retornar uma resposta JSON de sucesso
        return JsonResponse({'success': True})

    elif request.method == 'GET':
        # Se a solicitação for GET, renderize o template do formulário de pagamento
        form = PagamentoForm()
        return render(request, 'pagamento.html', {'form': form})
    else:
        # Se o método de solicitação não for permitido, retorne um erro 405
        return JsonResponse({'error': 'Método não permitido.'}, status=405)
    

## CLASS CUSTOMLOGIN
class CustomLoginView(LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('adicionar')

class CustomUserCreationView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')  # Redireciona para a página de login após o cadastro bem-sucedido

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

def home(request):
    return render(request, 'home.html', {'user': request.user})

def lista_enderecos(request):
    enderecos = Endereco.objects.all()
    return render(request, 'lista_enderecos.html', {'enderecos': enderecos})

@login_required
def adicionar_endereco(request):
    
    return render(request, 'adicionar_enderecos.html')

@login_required
def lista_pagamento(request):
    filtro = request.GET.get('filtro')

    # Filtra os pagamentos com base no filtro
    if filtro:
        pagamentos = Pagamento.objects.filter(
            Q(id__icontains=filtro) |
            Q(usuario__username__icontains=filtro) |
            Q(codigo_pagamento__icontains=filtro)
        )
    else:
        pagamentos = Pagamento.objects.all()

    # Obtém o usuário logado
    user_logado = request.user

    return render(request, 'lista_pagamento.html', {'pagamentos': pagamentos, 'user_logado': user_logado})



@login_required
def processar_pagamento(request):
    if request.method == 'POST':
        # Capturar os dados do POST
        usuario_id = request.POST.get('usuario_id')
        data_pagamento = request.POST.get('data_pagamento')
        codigo_pagamento = request.POST.get('codigo_pagamento')

        # Validar os dados (verificar se todos os campos foram enviados)
        if not usuario_id or not data_pagamento or not codigo_pagamento:
            return JsonResponse({'status': 'error', 'message': 'Todos os campos são obrigatórios.'})

        # Salvar os dados no banco de dados
        pagamento = Pagamento(usuario_id=usuario_id, data_pagamento=data_pagamento, codigo_pagamento=codigo_pagamento)
        pagamento.save()

        # Retornar uma resposta de sucesso
        return JsonResponse({'status': 'success', 'message': 'Pagamento processado com sucesso.'})
    else:
        # Se a requisição não for do tipo POST, retornar um erro
        return JsonResponse({'status': 'error', 'message': 'Método não permitido.'})

@login_required
def editar_pagamento(request, pagamento_id):
    # Busca o pagamento correspondente ao ID fornecido
    pagamento = get_object_or_404(Pagamento, pk=pagamento_id)
    
    # Verifica se o formulário foi submetido
    if request.method == 'POST':
        form = PagamentoForm(request.POST, instance=pagamento)
        if form.is_valid():
            form.save()
            return redirect('lista_pagamento')
    else:
        # Inicializa o formulário com os dados do pagamento
        form = PagamentoForm(instance=pagamento)
    
    return render(request, 'editar_pagamento.html', {'form': form, 'pagamento': pagamento})

@login_required
def excluir_pagamento(request, pagamento_id):
    # Busca o pagamento correspondente ao ID fornecido
    pagamento = get_object_or_404(Pagamento, pk=pagamento_id)
    
    # Verifica se o formulário foi submetido
    if request.method == 'POST':
        ic(pagamento)  # Debug: Verifica o pagamento antes de excluí-lo
        pagamento.delete()
        ic('Pagamento excluído com sucesso')  # Debug: Confirmação de exclusão bem-sucedida
        return redirect('lista_pagamento')
    else:
        ic(pagamento)  # Debug: Verifica o pagamento antes de renderizar a confirmação de exclusão
        return render(request, 'confirmar_exclusao_pagamento.html', {'pagamento': pagamento})

@login_required
def buscar_pagamentos(request):
    if request.method == 'GET':
        pagamento_id = request.GET.get('pagamento_id')
        if pagamento_id:
            try:
                # Busca o pagamento com base no ID fornecido
                pagamento = get_object_or_404(Pagamento, pk=pagamento_id)
                # Renderiza a tabela de pagamentos em HTML
                pagamentos_html = render_to_string('pagamentos_table.html', {'pagamentos': [pagamento]})

roteirizacao/templates/base2.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylebase.css' %}">
    <script src="{% static 'script2.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Sua Aplicação</title>

</head>
<body>
   <!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a
            href="#"
            class="list-group-item list-group-item-action py-2 ripple"
            aria-current="true"
          >
            <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Main dashboard</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple active">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Webiste traffic</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-lock fa-fw me-3"></i><span>Password</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-line fa-fw me-3"></i><span>Analytics</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fas fa-chart-pie fa-fw me-3"></i><span>SEO</span>
          </a>
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-chart-bar fa-fw me-3"></i><span>Orders</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-globe fa-fw me-3"></i><span>International</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-building fa-fw me-3"></i><span>Partners</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-calendar fa-fw me-3"></i><span>Calendar</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-users fa-fw me-3"></i><span>Users</span></a
          >
          <a href="#" class="list-group-item list-group-item-action py-2 ripple"
            ><i class="fas fa-money-bill fa-fw me-3"></i><span>Sales</span></a
          >
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
  
        <!-- Brand -->
        <a class="navbar-brand" href="#">
          <img
            src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
            height="25"
            alt="MDB Logo"
            loading="lazy"
          />
        </a>
        <!-- Search form -->
        <form class="d-none d-md-flex input-group w-auto my-auto">
          <input
            autocomplete="off"
            type="search"
            class="form-control rounded"
            placeholder='Search (ctrl + "/" to focus)'
            style="min-width: 225px;"
          />
          <span class="input-group-text border-0"><i class="fas fa-search"></i></span>
        </form>
  
        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">
          <!-- Notification dropdown -->
          <li class="nav-item dropdown">
            <a
              class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <i class="fas fa-bell"></i>
              <span class="badge rounded-pill badge-notification bg-danger">1</span>
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="#">Some news</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Another news</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Something else here</a>
              </li>
            </ul>
          </li>
  
          <!-- Icon -->
          <li class="nav-item">
            <a class="nav-link me-3 me-lg-0" href="#">
              <i class="fas fa-fill-drip"></i>
            </a>
          </li>
          <!-- Icon -->
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="#">
              <i class="fab fa-github"></i>
            </a>
          </li>
  
          <!-- Icon dropdown -->
          <li class="nav-item dropdown">
            <a
              class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow"
              href="#"
              id="navbarDropdown"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <i class="flag-united-kingdom flag m-0"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="#"
                  ><i class="flag-united-kingdom flag"></i>English
                  <i class="fa fa-check text-success ms-2"></i
                ></a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
              </li>
            </ul>
          </li>
  
          <!-- Avatar -->
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp"
                class="rounded-circle"
                height="22"
                alt="Avatar"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuLink"
            >
              <li>
                <a class="dropdown-item" href="#">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Logout</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>
  <!--Main Navigation-->
  
  <!--Main layout-->
  <main style="margin-top: 58px;">
    <div class="container pt-4"></div>
  </main>
  <!--Main layout--> 
  <script src="{% static 'script2.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

roteirizacao/templates/confirmar_exclusao_pagamento.html
{% extends 'base.html' %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div>
        <h1>Confirmar Exclusão</h1>
        <p>Você está prestes a excluir o pagamento com ID: {{ pagamento.id }}. Tem certeza que deseja continuar?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
        </form>
    </div>
</div>
{% endblock %}

roteirizacao/templates/envia_email.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<form action="{% url 'enviar_email' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>


{% endblock %}

roteirizacao/templates/pagamento.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="pagamento-container">
  <form method="post" class="payment-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_usuario">Usuário:</label>
      {{ form.usuario }}
    </div>
    <div class="form-group">
      <label for="id_codigo_pagamento">Código de Pagamento:</label>
      <input type="text" id="id_codigo_pagamento" name="codigo_pagamento" class="form-control" readonly>
      <button type="button" class="btn btn-primary" id="gerar-codigo-pagamento">Gerar Código</button>
    </div>
    <div class="form-group">
      <label for="id_data_pagamento">Data de Pagamento:</label>
      <input type="date" id="id_data_pagamento" name="data_pagamento" class="form-control">

    </div>
    <div class="form-group">
      <label for="id_valido_ate">Válido até:</label>
      <input type="text" id="id_valido_ate" name="valido_ate" class="form-control" readonly>
    </div>
    <div class="form-group">
      <label for="id_quant_acesso">Quantidade de Acessos:</label>
      <input type="number" id="id_quant_acesso" name="quant_acesso" class="form-control" value="30" readonly>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</div>
{% endblock %}